build:
	@echo "Compiling code.."
	@g++ -ansi -std=c++11 -lm inverzit.cpp -o inverzit
	@echo "Done!"

test:
	@echo "Compiling code.."
	@g++ -ansi -std=c++11 -lm test.cpp -o test
	@echo "Done!"

clean:
	@echo "Removing.."
	@rm inverzit
	@rm ki.txt
	@echo "Done"
